//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTobaccoShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int O_ID { get; set; }
        public int O_QUANTITY { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int PRODUCT_ID { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
