//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTobaccoShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int U_ID { get; set; }
        public string U_FULLNAME { get; set; }
        public string U_EMAIL { get; set; }
        public string U_USERNAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_TYPE { get; set; }


        public override string ToString()
        {
            return $"User details :\nId : {U_ID}\nName : {U_FULLNAME}\nEmail : {U_EMAIL}\nUsername : {U_USERNAME}\nPassword : ************\nType : {U_TYPE}";
        }
    }

}
